//HintName: TestClass.XmlSpecified.g.cs
// <auto-generated/>
#nullable enable

namespace TestNamespace
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSpecified")]
    partial class TestClass
    {
        /// <summary>
        /// Gets a value indicating whether <see cref="IsDeleted"/> should be serialized.
        /// </summary>
        [global::System.Xml.Serialization.XmlIgnore]
        public bool IsDeletedSpecified => !IsDeleted;
    }
}
