using System;
using System.Collections.Generic;
using System.Linq;
using XmlSpecified.Generator.Models;

namespace XmlSpecified.Generator.Utilities;

/// <summary>
/// Builds the generated source code for Specified properties.
/// </summary>
internal sealed class SpecifiedCodeBuilder
{
    private readonly PropertyContainer _propertyContainer;
    private readonly List<PropertyData> _properties;
    private readonly string _version;

    /// <summary>
    /// Initializes a new instance of the SpecifiedCodeBuilder.
    /// </summary>
    internal SpecifiedCodeBuilder(PropertyContainer propertyContainer, string version)
    {
        _propertyContainer = propertyContainer;
        _properties = new List<PropertyData>();
        _version = version;
    }

    /// <summary>
    /// Adds a property to generate a Specified property for.
    /// </summary>
    internal void AddProperty(PropertyData propertyData)
    {
        _properties.Add(propertyData);
    }

    /// <summary>
    /// Builds the complete source code.
    /// </summary>
    internal string Build()
    {
        // Sort properties for deterministic output
        _properties.Sort((a, b) => StringComparer.Ordinal.Compare(a.PropertyName, b.PropertyName));
        var usingLinq = _properties.Any(x => x.PropertyType.IsEnumerable);

        var sb = new IndentedStringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (usingLinq)
        {
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();
        }

        // Namespace
        if (!string.IsNullOrEmpty(_propertyContainer.Namespace))
        {
            sb.AppendLine($"namespace {_propertyContainer.Namespace}");
            sb.AppendLine("{");
            sb.IncreaseIndent();
        }

        // Open classes
        foreach (var parentClass in _propertyContainer.PropertyClasses)
        {
            sb.AppendLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
            sb.AppendLine(
                $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"XmlSpecified\", \"{_version}\")]"
            );
            sb.AppendLine($"partial {parentClass.Keyword} {parentClass.Name}");
            sb.AppendLine("{");
            sb.IncreaseIndent();
        }

        // Generate each property
        var isFirst = true;
        foreach (var property in _properties)
        {
            var checkExpression = ExpressionGenerator.GenerateCheckExpression(property);

            if (!isFirst)
            {
                sb.AppendLine();
            }
            isFirst = false;

            sb.AppendLine($"/// <summary>");
            sb.AppendLine(
                $"/// Gets a value indicating whether <see cref=\"{property.PropertyName}\"/> should be serialized."
            );
            sb.AppendLine($"/// </summary>");
            sb.AppendLine($"[global::System.Xml.Serialization.XmlIgnore]");
            sb.AppendLine($"public bool {property.PropertyName}Specified => {checkExpression};");
        }

        // Close classes
        foreach (var parentClass in _propertyContainer.PropertyClasses)
        {
            sb.DecreaseIndent();
            sb.AppendLine("}");
        }

        // Close namespace
        if (!string.IsNullOrEmpty(_propertyContainer.Namespace))
        {
            sb.DecreaseIndent();
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
