using System;
using System.Collections.Generic;
using XmlSpecified.Generator.Models;

namespace XmlSpecified.Generator.Utilities;

/// <summary>
/// Builds the generated source code for Specified properties.
/// </summary>
internal sealed class SpecifiedCodeBuilder
{
    private readonly PropertyContainer _propertyContainer;
    private readonly List<PropertyInfo> _properties;
    private readonly string _version;
    private bool _addLinqUsingStatement;

    /// <summary>
    /// Initializes a new instance of the SpecifiedCodeBuilder.
    /// </summary>
    public SpecifiedCodeBuilder(PropertyContainer propertyContainer, string version)
    {
        _propertyContainer = propertyContainer;
        _properties = new List<PropertyInfo>();
        _version = version;
        _addLinqUsingStatement = false;
    }

    /// <summary>
    /// Information about a property to generate a Specified property for.
    /// </summary>
    private readonly record struct PropertyInfo
    {
        public string Name { get; init; }
        public string CheckExpression { get; init; }
    }

    /// <summary>
    /// Adds a property to generate a Specified property for.
    /// </summary>
    public void AddProperty(PropertyData propertyData)
    {
        _properties.Add(
            new PropertyInfo
            {
                Name = propertyData.PropertyName,
                CheckExpression = ExpressionGenerator.GenerateCheckExpression(propertyData),
            }
        );

        if (propertyData.PropertyType.IsEnumerable)
        {
            _addLinqUsingStatement = true;
        }
    }

    /// <summary>
    /// Builds the complete source code.
    /// </summary>
    public string Build()
    {
        var sb = new IndentedStringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (_addLinqUsingStatement)
        {
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();
        }

        // Namespace
        if (!string.IsNullOrEmpty(_propertyContainer.Namespace))
        {
            sb.AppendLine($"namespace {_propertyContainer.Namespace}");
            sb.AppendLine("{");
            sb.IncreaseIndent();
        }

        // Open classes
        foreach (var parentClass in _propertyContainer.PropertyClasses)
        {
            sb.AppendLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
            sb.AppendLine(
                $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"XmlSpecified\", \"{_version}\")]"
            );
            sb.AppendLine($"partial {parentClass.Keyword} {parentClass.Name}");
            sb.AppendLine("{");
            sb.IncreaseIndent();
        }

        // Sort properties for deterministic output
        _properties.Sort((a, b) => StringComparer.Ordinal.Compare(a.Name, b.Name));

        // Generate each property
        var isFirst = true;
        foreach (var property in _properties)
        {
            if (!isFirst)
            {
                sb.AppendLine();
            }
            isFirst = false;

            sb.AppendLine($"/// <summary>");
            sb.AppendLine(
                $"/// Gets a value indicating whether <see cref=\"{property.Name}\"/> should be serialized."
            );
            sb.AppendLine($"/// </summary>");
            sb.AppendLine($"[global::System.Xml.Serialization.XmlIgnore]");
            sb.AppendLine($"public bool {property.Name}Specified => {property.CheckExpression};");
        }

        // Close classes
        foreach (var parentClass in _propertyContainer.PropertyClasses)
        {
            sb.DecreaseIndent();
            sb.AppendLine("}");
        }

        // Close namespace
        if (!string.IsNullOrEmpty(_propertyContainer.Namespace))
        {
            sb.DecreaseIndent();
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
